"""initial tables

Revision ID: 9780e05b3c08
Revises: 
Create Date: 2026-05-04 07:11:46.151107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9780e05b3c08'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('owasp_category', sa.String(length=100), nullable=True),
    sa.Column('phase', sa.String(length=10), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('request_snapshot', sa.JSON(), nullable=True),
    sa.Column('response_snapshot', sa.JSON(), nullable=True),
    sa.Column('payload_used', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('remediation', sa.Text(), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=True),
    sa.Column('is_false_positive', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learned_schemas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('request_fields', sa.JSON(), nullable=True),
    sa.Column('response_fields', sa.JSON(), nullable=True),
    sa.Column('status_codes', sa.JSON(), nullable=True),
    sa.Column('avg_latency_ms', sa.Float(), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('is_stable', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learned_schemas_endpoint'), 'learned_schemas', ['endpoint'], unique=False)
    op.create_table('scan_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('target_url', sa.String(length=500), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('base_request', sa.JSON(), nullable=True),
    sa.Column('attack_types', sa.JSON(), nullable=True),
    sa.Column('max_requests', sa.Integer(), nullable=True),
    sa.Column('requests_per_second', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('total_requests_sent', sa.Integer(), nullable=True),
    sa.Column('findings_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('traffic_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=False),
    sa.Column('full_url', sa.Text(), nullable=False),
    sa.Column('request_headers', sa.JSON(), nullable=True),
    sa.Column('request_body', sa.Text(), nullable=True),
    sa.Column('query_params', sa.JSON(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_headers', sa.JSON(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('source_ip', sa.String(length=50), nullable=True),
    sa.Column('session_id', sa.String(length=200), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=10), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('is_flagged', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_traffic_endpoint_method', 'traffic_logs', ['endpoint', 'method'], unique=False)
    op.create_index(op.f('ix_traffic_logs_endpoint'), 'traffic_logs', ['endpoint'], unique=False)
    op.create_index(op.f('ix_traffic_logs_timestamp'), 'traffic_logs', ['timestamp'], unique=False)
    op.create_index('ix_traffic_timestamp_risk', 'traffic_logs', ['timestamp', 'risk_level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_traffic_timestamp_risk', table_name='traffic_logs')
    op.drop_index(op.f('ix_traffic_logs_timestamp'), table_name='traffic_logs')
    op.drop_index(op.f('ix_traffic_logs_endpoint'), table_name='traffic_logs')
    op.drop_index('ix_traffic_endpoint_method', table_name='traffic_logs')
    op.drop_table('traffic_logs')
    op.drop_table('scan_jobs')
    op.drop_index(op.f('ix_learned_schemas_endpoint'), table_name='learned_schemas')
    op.drop_table('learned_schemas')
    op.drop_table('findings')
    # ### end Alembic commands ###
